### PR TITLE
Fix timeline for Node.js and others

### PR DESCRIPTION
**Pull request by umarov**

### CODE REVIEW

**Review by nburwell — APPROVED** [review]
Thanks, looks good!

BTW, I'm (re) remembering that we don't actually show the timeline or even the main description in the tech radar UI - we should! Could be a good passion project for someone..

**Comment by umarov** [comment]
I think this broke it. Node.js is back to access

**Comment by umarov** [comment]
I will change the ordering in the timeline

**Comment by umarov** [comment]
Different ordering fixed it

**Pull request merged**
